### ISSUE TITLE
http server code hangs after generating cert & key

### ISSUE THREAD

**Issue by AndrewBazen** [AndrewBazen/CS469_small_group_project#5]
currently the server code is hanging after ssl generation.  I believe this is due to a port confliction.

**Comment by b-a-merritt** [comment]
This is the error I get when making a request to the server
```Bash
0078B7F7E7F0000:error:0A00009C:SSL routines:ssl3_get_record:http request:../ssl/record/ssl3_record.c:345:
```

**Comment by AndrewBazen** [comment]
> This is the error I get when making a request to the server
> 
> 0078B7F7E7F0000:error:0A00009C:SSL routines:ssl3_get_record:http request:../ssl/record/ssl3_record.c:345:

can you show more of the printout?

**Comment by b-a-merritt** [comment]
That is the only log after 
```
SSL certificate and key generated.
```

I got that by just visiting localhost:4433 in the browser to make a quick get request to the server (I wanted to see if it was on)

**Comment by AndrewBazen** [comment]
✔ Container http-server  Recreated                                      0.0s 
 ✔ Container mysql        Recreated                                      0.0s 
Attaching to http-server, mysql
mysql        | 2024-10-02 10:33:47+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
mysql        | 2024-10-02 10:33:47+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql        | 2024-10-02 10:33:47+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
mysql        | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql        | 2024-10-02T10:33:48.054728Z 0 [System] [MY-015015] [Server] MySQL Server - start.
mysql        | 2024-10-02T10:33:48.223221Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 9.0.1) starting as process 1
mysql        | 2024-10-02T10:33:48.230632Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql        | 2024-10-02T10:33:48.348470Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql        | 2024-10-02T10:33:48.496673Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql        | 2024-10-02T10:33:48.496694Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql        | 2024-10-02T10:33:48.498584Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql        | 2024-10-02T10:33:48.514885Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mysql        | 2024-10-02T10:33:48.514914Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '9.0.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
http-server  | Generating SSL certificate and key...
http-server  | .....+.....+.+..........................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+.+......+.....+...+......+...+.+.....+.+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+..............+....+.....+.+...+..+.+..............+.........+....+..+...+..........+..+.........+.+...........+..................+.........+.......+.....+.+........+....+...+.....+..........+.................+................+..+....+.....+...+...............+......+....+..+.+..+...+..........+...+..+............+.+......+........+......+..........+.....+.+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
http-server  | ..+...+........+......+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+...+..+.......+......+..................+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
http-server  | -----
http-server  | SSL certificate and key generated.

this is the output I get, and this is the spot where it hangs

**Comment by AndrewBazen** [comment]
server is listening on the port, however it doesn't output the print statements for the socket creation and listening until the server received an incoming connection.

**Comment by AndrewBazen** [comment]
making a new issue
